# Generated by Django 5.0.6 on 2024-09-24 16:19

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=299, verbose_name='Вопрос')),
                ('Image', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=99, verbose_name='Ответ')),
                ('flag', models.BooleanField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.questions', verbose_name='Связанный вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99, verbose_name='Название')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=299, verbose_name='Описание')),
                ('slug', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Альт.название')),
                ('is_published', models.BooleanField(choices=[(False, 'Неопубликовано'), (True, 'Опубликовано')], default=0, verbose_name='Статус')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='tests_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.tests', verbose_name='Связанный тест'),
        ),
    ]
